apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web
        image: {{ .Values.image}}
      - name: app
        image: {{ .Values.image}}
      - name: db
        image: {{ .Values.image}}