apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  labels:
    app: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}
          args:
            - --self-url={{ .Values.app.selfURL }}
          ports:
            - containerPort: {{ .Values.service.port }}