apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    - protocol: TCP 
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: app
    tier: app
  type: ClusterIP