apiVersion: v2
name: web
version: 1.0.0
description: A Helm chart to deploy the web application to the web namespace
dependencies:
  - name: nginx-ingress-controller
    repository: https://ghcr.io/nginxinc/charts/nginx-ingress
    version: 1.1.0