replicaCount: 1
image:
  repository: nginx
  tag: latest
service:
  name: {{ .Values.service.name }}
  port: 80
ingress:
  enabled: true
  hosts:
    - host: test.local
      paths:
        - /
namespace: web